specfile_path: fmf.spec
synced_files:
    - fmf.spec

upstream_project_name: fmf
downstream_package_name: fmf

current_version_command: ["make", "packit-version"]

actions:
  create-archive:
  - make packit-tarball
  - make packit-path

jobs:
  - job: tests
    trigger: pull_request
    metadata:
      targets:
      - fedora-all
