language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
before_install:
  - "pip install -U pip setuptools virtualenv coveralls PyYAML"
script:
  - "coverage run --source=bin,fmf -m py.test $CAPTURE tests"
after_success:
  - coveralls
  - coverage report
# Hint: To enable more detailed logging for debugging purposes,
# define the following variables in the Travis CI web interface
#
# CAPTURE=--capture=no
# DEBUG=5
